/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Product;

/**
 *
 * @author tirthnaik
 */
public class VoluntaryFormJPanel extends javax.swing.JPanel {

    Product product;
    
    /**
     * Creates new form SampleJPanel
     */
    public VoluntaryFormJPanel(Product p) {
        initComponents();
        product = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnDarkMode = new javax.swing.JToggleButton();
        boxSouthAsian = new javax.swing.JCheckBox();
        rbtnMale = new javax.swing.JRadioButton();
        comboboxVeteran = new javax.swing.JComboBox<>();
        boxAmerican = new javax.swing.JCheckBox();
        lblSexualIdentity = new javax.swing.JLabel();
        rbtnFemale = new javax.swing.JRadioButton();
        lblEthnicity = new javax.swing.JLabel();
        boxBlack = new javax.swing.JCheckBox();
        boxAmericanIndian = new javax.swing.JCheckBox();
        lblVeteran = new javax.swing.JLabel();

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Voluntary Information");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDarkMode.setText("Dark Mode");
        btnDarkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarkModeActionPerformed(evt);
            }
        });

        boxSouthAsian.setText("South Asian");
        boxSouthAsian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSouthAsianActionPerformed(evt);
            }
        });

        rbtnMale.setText("Male");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });

        comboboxVeteran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one ", "Not a Protected Veteran", "Protected Veteran", "None of the above", " " }));
        comboboxVeteran.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboboxVeteranAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        comboboxVeteran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxVeteranActionPerformed(evt);
            }
        });

        boxAmerican.setText("American");
        boxAmerican.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAmericanActionPerformed(evt);
            }
        });

        lblSexualIdentity.setText("Sexual Identity");

        rbtnFemale.setText("Female");
        rbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemaleActionPerformed(evt);
            }
        });

        lblEthnicity.setText("Ethnicity");

        boxBlack.setText("Black");
        boxBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxBlackActionPerformed(evt);
            }
        });

        boxAmericanIndian.setText("American Indian");
        boxAmericanIndian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAmericanIndianActionPerformed(evt);
            }
        });

        lblVeteran.setText("Veteran");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnDarkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVeteran, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSexualIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnFemale)
                                    .addComponent(rbtnMale))))
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxAmerican)
                            .addComponent(lblEthnicity, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxSouthAsian)
                            .addComponent(boxBlack)
                            .addComponent(boxAmericanIndian)))
                    .addComponent(comboboxVeteran, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDarkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEthnicity, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblSexualIdentity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMale)
                    .addComponent(boxAmerican))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnFemale)
                    .addComponent(boxSouthAsian))
                .addGap(18, 18, 18)
                .addComponent(boxBlack)
                .addGap(18, 18, 18)
                .addComponent(boxAmericanIndian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lblVeteran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboboxVeteran, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void boxSouthAsianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSouthAsianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSouthAsianActionPerformed

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
        if(rbtnMale.isSelected()){
            rbtnFemale.setSelected(false);
        }
    }//GEN-LAST:event_rbtnMaleActionPerformed

    private void btnDarkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarkModeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDarkModeActionPerformed

    private void boxAmericanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAmericanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxAmericanActionPerformed

    private void rbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemaleActionPerformed
        // TODO add your handling code here:
        if(rbtnFemale.isSelected()){
            rbtnMale.setSelected(false);
        }
    }//GEN-LAST:event_rbtnFemaleActionPerformed

    private void boxBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxBlackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxBlackActionPerformed

    private void boxAmericanIndianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAmericanIndianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxAmericanIndianActionPerformed

    private void comboboxVeteranAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboboxVeteranAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxVeteranAncestorAdded

    private void comboboxVeteranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxVeteranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxVeteranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxAmerican;
    private javax.swing.JCheckBox boxAmericanIndian;
    private javax.swing.JCheckBox boxBlack;
    private javax.swing.JCheckBox boxSouthAsian;
    private javax.swing.JToggleButton btnDarkMode;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboboxVeteran;
    private javax.swing.JLabel lblEthnicity;
    private javax.swing.JLabel lblSexualIdentity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVeteran;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    // End of variables declaration//GEN-END:variables
}
